### ISSUE TITLE
“'module' object has no attribute 'broadcast_to'” when I try to train on other dataset.

### ISSUE THREAD

**Issue by Yansslc** [DetectionTeamUCAS/FCOS_Tensorflow#10]
HI, I 'm trying to train on other dataset using your code, but when I run multi_gpu_train.py, the error occured. Does anyone know how to solve it? The error is detailed in the picture below.

**Comment by Yansslc** [comment]
![1](https://user-images.githubusercontent.com/42287555/60149267-acedc480-9806-11e9-936b-e836a859fbc6.png)

**Comment by yangxue0827** [comment]
update your tensorflow version to 1.12 @Yansslc

**Comment by Yansslc** [comment]
Thanks a lot! Problem solved~
But there is a new error and I don't know what caused it, can you help me? 
![2](https://user-images.githubusercontent.com/42287555/60172337-0c67c680-983f-11e9-9207-959de51119b7.png)

**Comment by yangxue0827** [comment]
The latest code has been updated, and the performance has been greatly improved.
