### ISSUE TITLE
About the fcos_target

### ISSUE THREAD

**Issue by mysephi** [DetectionTeamUCAS/FCOS_Tensorflow#16]
line61 and 62 in FCOS_Tensorflow/libs/detection_oprations/fcos_target.py
1e5 <= off_max_xy <= 0 when fm_i equals 0, which means no targets in that layer.

**Comment by yangxue0827** [comment]
you are right, thx!

**Comment by yangxue0827** [comment]
The bug has been fixed, and the performance is improved from 73.55% to 74.37%. Thx, bro!
