### ISSUE TITLE
Training on own dataset

### ISSUE THREAD

**Issue by nassarofficial** [DetectionTeamUCAS/FCOS_Tensorflow#2]
Hello,
When I am training using my own dataset created using tfrecords I get this error at the same step always:

> tensorflow.python.framework.errors_impl.OutOfRangeError: PaddingFIFOQueue '_1_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 4, current size 0)
>          [[node get_batch/batch (defined at ../data/io/read_tfrecord.py:98) ]]

**Comment by yangxue0827** [comment]
Something wrong with your tfrecord. @nassarofficial

**Comment by reeceshearsmith** [comment]
hello, can you release  convert_data_to_tfrecord_coco.py ?
thank you

**Comment by yangxue0827** [comment]
https://github.com/DetectionTeamUCAS/Cascade_FPN_Tensorflow/blob/master/data/io/convert_data_to_tfrecord_coco.py

You need to make some modify because I'm not using the official json format. @reeceshearsmith

**Comment by reeceshearsmith** [comment]
Thank you very much @yangxue0827

**Comment by yangxue0827** [comment]
This repo has not been reproduced, still in debugging. @reeceshearsmith

**Comment by reeceshearsmith** [comment]
Thanks for informing : )
