### ISSUE TITLE
Difference in accuracy with Resnet101 backbone

### ISSUE THREAD

**Issue by anushl9o5** [DetectionTeamUCAS/FCOS_Tensorflow#4]
Hi, I would like to know how much improvement is the resnet101 backbone going to give when compared to the resnet50 version, in terms of accuracy, given that the model is still not performing up to the papers standards  
Thanks!

**Comment by yangxue0827** [comment]
i am still debugging @anushl9o5

**Comment by yangxue0827** [comment]
The latest code has been updated, and the performance has been greatly improved.
