### ISSUE TITLE
No module named 'libs.box_utils.nms.gpu_nms'

### ISSUE THREAD

**Issue by ZhengyuZhang96** [DetectionTeamUCAS/FCOS_Tensorflow#7]
Hello author , thank you very much for sharing the code！

but when i am using you code , i meet this porblem : No module named 'libs.box_utils.nms.gpu_nms'

how can i solve it ?

**Comment by yangweixiang** [comment]
cd $PATH_ROOT/libs/box_utils/cython_utils
python setup.py build_ext --inplace

cd $PATH_ROOT/libs/box_utils/nms
python setup.py build_ext --inplace
