### ISSUE TITLE
rpn_cls_loss turns to zero

### ISSUE THREAD

**Issue by yangweixiang** [DetectionTeamUCAS/FCOS_Tensorflow#9]
I download the source code and try to reproduce the result . but get a issue.

environment：
resnet_v1_50
cfgs.py（FCOS_Tensorflow/libs/configs）
4GPUS  (GPU_GROUP = "1,3,4,7") 

2019-06-17 16:11:41: global_step:80  current_step:80
per_cost_time:2.604s
rpn_cls_loss:1.194
rpn_bbox_loss:2.896
rpn_ctr_loss:0.694
total_losses:4.784

after 4640 step, the rpn_cls_loss turns to very small
2019-06-17 16:41:28: global_step:4640  current_step:4640
per_cost_time:0.254s
rpn_cls_loss:0.090
rpn_bbox_loss:1.299
rpn_ctr_loss:0.602
total_losses:1.991

************************************************************
2019-06-17 18:12:14: global_step:18960  current_step:18960
per_cost_time:0.225s
rpn_cls_loss:0.004
rpn_bbox_loss:1.242
rpn_ctr_loss:0.568
total_losses:1.814

2019-06-17 21:52:52: global_step:53280  current_step:53280
per_cost_time:0.224s
rpn_cls_loss:0.001
rpn_bbox_loss:1.161
rpn_ctr_loss:0.573
total_losses:1.735

************************************************************
2019-06-17 21:59:09: global_step:54240  current_step:54240
per_cost_time:0.241s
rpn_cls_loss:0.000
rpn_bbox_loss:1.166
rpn_ctr_loss:0.571
total_losses:1.737

Is there anyone met this issue ?

And I review the source code related with rpn_cls_loss , but failed to find the root cause.

**fcos_target.py
def fcos_target(gt_boxes, image_batch, fm_size_list):**

**losses_fcos.py
def focal_loss(pred, label, background=0, alpha=0.5, gamma=2.0):**

**Comment by LCWdmlearning** [comment]
hello ,have you solved this problem yet?，I have the same problem.

**Comment by yangweixiang** [comment]
> hello ,have you solved this problem yet?，I have the same problem.

not yet

**Comment by yangxue0827** [comment]
The latest code has been updated, and the performance has been greatly improved.
